name: Zedd-App_CI

on:
  push:
    # Triggers workflow whenever push is performed on each branch containing "feature/..."
    branches: [ "feature/**" ]

jobs:
  build:
  
    # The type of runner that the job will run on
    runs-on: ${{matrix.os}}
    
    # Strategy for performing jobs in multiple enviroments
    strategy:
      matrix: 
        node-version: [16.x]
        os: [windows-latest, macos-latest]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run npm ci
        working-directory: ./zedd-clarity
        run: npm ci --legacy-peer-deps
      - name: Run npm build
        working-directory: ./zedd-clarity
        run: npm run build    
      - name: Run npm ci
        working-directory: ./zedd-app
        run: npm ci --legacy-peer-deps
      - name: Run test
        working-directory: ./zedd-app
        run: npm test
          

