name: Zedd-App_CI

on:
  push:
    branches: [ "feature/**" ]

jobs:
  build:
  
    runs-on: ${{matrix.os}}
    
    strategy:
      matrix: 
        node-version: [16.x]
        os: [windows-latest, macos-latest]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run clarity
        working-directory: ./zedd-clarity
        run: npm ci --force
      - name: Run clarity
        working-directory: ./zedd-clarity
        run: npm run build
      - name: Run test
        working-directory: ./zedd-app
        run: npm ci --force
      - name: Run test
        working-directory: ./zedd-app
        run: npm test
          

