name: Zedd-App_CI

on:
  push:
    branches: [ "feature/**" ]

jobs:
  build:
  
    runs-on: ${{matrix.os}}
    defaults:
      run:
        working-directory: ./zedd-app
    
    strategy:
      matrix: 
        node-version: [8.x]
        os: [windows-latest, macos-latest]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run npm install
        run: npm ci --force
      - name: Run npm build
        run: npm build
      - name: Run npm test
        run: npm test

          

